[package]
name = "rays"
version = "0.1.0"
authors = ["expert700 <dyllancole@outlook.com>"]
edition = "2018"

[dependencies]
"nalgebra" = "0.17.0"
"rand" = "0.6.5"

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "benchmark"
harness = false